### PR TITLE
Fix Particle adapter

### PR DESCRIPTION
**Pull request by jordaaash**

### CODE REVIEW

**Comment by jordaaash** [comment]
@TABASCOatw the build should be passing now, can you test this out?

I've changed the config API slightly to simplify the types which we can just inherit from the functions we need to call.

**Comment by TABASCOatw** [comment]
> @TABASCOatw the build should be passing now, can you test this out?
> 
> I've changed the config API slightly to simplify the types which we can just inherit from the functions we need to call.

Hey @jordaaash, thank you for making these changes and putting these together, big help! Just gave this a try in my testing environment + local build, seems to be working well! Tested all major functions of the adapter with the modifications made, all good.

**Comment by jordaaash** [comment]
Awesome, thanks!

**Comment by jordaaash** [comment]
Released via https://github.com/solana-labs/wallet-adapter/pull/878

**Comment by vitalikda** [comment]
@jordaaash just updated the `@solana/wallet-adapter-wallets` package to v0.19.25

Got this error:  `Module not found: Can't resolve '@particle-network/auth'`

Guessing not all libs were updated? `"@solana/wallet-adapter-particle": "^0.1.10",`

**Comment by jordaaash** [comment]
@vitalikda Hmm, it should be?

https://github.com/solana-labs/wallet-adapter/pull/878/files#diff-89b3ea5f25ee48fc8b0140e47d656ff245f0fb6c5c038d5b35760347b1fbb5a3L57

This line specifies to use the latest workspace version on release, which is `0.1.11` for Particle now.

If I run `npm info @solana/wallet-adapter-wallets` it looks right?

```
@solana/wallet-adapter-wallets@0.19.25 | Apache-2.0 | deps: 36 | versions: 94
<!-- @TODO -->
https://github.com/solana-labs/wallet-adapter#readme

dist
.tarball: https://registry.npmjs.org/@solana/wallet-adapter-wallets/-/wallet-adapter-wallets-0.19.25.tgz
.shasum: e6611ca48c2bff210934b8d33148bf77600b6422
.integrity: sha512-gk25fVa4HgB+3x4mqyr9fN3emp9TcEm8Rk2kVn3LZWzI01fmWVHA0TwaVnvN7bNycBc4MTCfQwP1HiELJloC+Q==
.unpackedSize: 28.3 kB

dependencies:
[...snip...]
@solana/wallet-adapter-particle: ^0.1.11
```

**Comment by vitalikda** [comment]
@jordaaash sorry, I wrongly assumed this PR removed `@particle-network/auth` 
Looks like it's an issue in `@particle-network/solana-wallet` that requires it as a peer dep 
```
yarn info @particle-network/solana-wallet

  peerDependencies: {
    '@particle-network/auth': '*',
    '@solana/web3.js': '^1.50.1',
    bs58: '^4.0.1'
  },
```

Also, there is a related issue opened: https://github.com/solana-labs/wallet-adapter/issues/880

**Comment by jordaaash** [comment]
@TABASCOatw can you make this a dependency of `@particle-network/solana-wallet` if it's required, or remove it if not?

I don't think it makes sense for us to make `@particle-network/auth` a dependency here, as we don't import it anywhere.

**Comment by TABASCOatw** [comment]
> @TABASCOatw can you make this a dependency of `@particle-network/solana-wallet` if it's required, or remove it if not?
> 
> I don't think it makes sense for us to make `@particle-network/auth` a dependency here, as we don't import it anywhere.

Sure, no problem. Will check and see if we can throw it as a dependency asap; `@particle-network/auth` drives the social login functionality.

**Comment by jordaaash** [comment]
Okay, thanks! Let me know if that's released and we can update the version we depend on here.

**Comment by jordaaash** [comment]
@TABASCOatw any update? We need to get this fixed or revert the changes to the Particle adapter so it doesn't break consuming projects.

**Comment by TABASCOatw** [comment]
> @TABASCOatw any update? We need to get this fixed or revert the changes to the Particle adapter so it doesn't break consuming projects.

Gotcha, will share an update here before EOD. May need to go down the route of reverting and waiting for a fix, but will check again to see if we can switch those dependencies today.

**Comment by TABASCOatw** [comment]
> > @TABASCOatw any update? We need to get this fixed or revert the changes to the Particle adapter so it doesn't break consuming projects.
> 
> Gotcha, will share an update here before EOD. May need to go down the route of reverting and waiting for a fix, but will check again to see if we can switch those dependencies today.

May need to revert for now (unless you'd like to add the dependency manually, but needs to be fixed on our end tbh), will put together a fix with my team asap and regroup on this. Thanks for your help here, apologies for the issues!

**Comment by jordaaash** [comment]
@TABASCOatw when do you think you can get the fix in? Since this was released broken, I'll have to push a release either way, so would prefer not to have to release twice!

**Comment by TABASCOatw** [comment]
> @TABASCOatw when do you think you can get the fix in? Since this was released broken, I'll have to push a release either way, so would prefer not to have to release twice!

Not 100% sure, pretty tight developer bandwidth at the moment on our end, so it's a bit difficult to fit this in even though it's a pretty small change, but I think we'll probably have it pushed by EOW next week, probably the next 5 or so days.

**Comment by jordaaash** [comment]
@TABASCOatw Okay, it's a 1 line change to add this dependency where it should be, and it's breaking the build here. Please publish it soon! I regret merging this change and will have to roll it back otherwise.

**Comment by TABASCOatw** [comment]
> @TABASCOatw Okay, it's a 1 line change to add this dependency where it should be, and it's breaking the build here. Please publish it soon! I regret merging this change and will have to roll it back otherwise.

I've emphasized the importance of this to my team and do my best to have it merged within the next 24 hours, otherwise a rollback may be the best option if it isn't merged before then. Apologies for the issues here once again

**Comment by TABASCOatw** [comment]
> @TABASCOatw Okay, it's a 1 line change to add this dependency where it should be, and it's breaking the build here. Please publish it soon! I regret merging this change and will have to roll it back otherwise.

Update: We've pushed the new version of `@particle-network/solana-wallet` which incudes `@particle-network/auth` as a core dependency. https://www.npmjs.com/package/@particle-network/solana-wallet

**Pull request merged**
