### PR TITLE
Optimize `onError`

### PR DESCRIPTION
**Pull request by jordansexton**
This addresses https://github.com/solana-labs/wallet-adapter/pull/637#discussion_r1008769669

Per https://github.com/solana-labs/wallet-adapter/pull/637#discussion_r1008769819 there may be a better way of doing this

### CODE REVIEW

**Comment by steveluscher** [comment]
I like this slightly better, since you don't have to build up the error handler implementation in two places. Squash and merge if you agree!

**Comment by jordansexton** [comment]
Haha I tried it this way too. There's gotta be a better way to do default prop values of functions than passing a ref into a ref right?

**Comment by jordansexton** [comment]
I'll add a changeset so we can release it from here.

**Comment by steveluscher** [comment]
I mean,
1. The great thing about refs is they don't get ‘passed’ into anything. Even if you use them as a dependency, they will _never change_. They are a wrapper around a value, and the wrapped is 100% stable.
2. The first ref wraps the custom upstream handler, and the second ref implements the actual handler, so they're usefully different.

**Pull request merged**
