### PR TITLE
Add WELLDONE Wallet Adapter

### PR DESCRIPTION
**Pull request by sunny0529**
This PR adds WELLDONE Wallet to the Solana Wallet-Adapter.

WELLDONE is an extension based multi-chain wallet.
Users can transfer tokens, connect dApps, or use bridges(neon) across different blockchains in a single platform.

* Minimum wallet version is 0.0.22. It will update tomorrow. After updating, I will comment on this PR page!

### CODE REVIEW

**Comment by sunny0529** [comment]
Now our wallet has been updated to version 0.0.22.
Please test it and review PR.

**Comment by sunny0529** [comment]
@jordansexton Please review my PR.

**Comment by jordansexton** [comment]
@sunny0529 thanks for the PR, no need to keep commenting. I'll review when I can! In the meantime, please check out https://github.com/wallet-standard/wallet-standard

Very soon, all wallets will be asked to implement this and new adapters will be phased out.

**Comment by jordansexton** [comment]
Thanks for your contribution. We are no longer accepting PRs of adapters for this type of wallet. You can [read about this policy here](https://github.com/solana-labs/wallet-adapter/blob/master/WALLET.md), but more importantly, please check out [this guide for wallets](https://github.com/solana-labs/wallet-standard/blob/master/WALLET.md) to implement the Wallet Standard.

However, most of what you've written for this adapter is portable to the Wallet Standard interface, and implementing this interface will grant your wallet distribution on dapps across Solana.

After reading the guide and looking at the reference implementations, if you have questions on how to do this, please open an issue on the https://github.com/solana-labs/wallet-standard repo.

**Pull request closed without merging**
