### PR TITLE
Changes for Next.js support

### PR DESCRIPTION
**Pull request by jordansexton**
re: https://github.com/solana-labs/wallet-adapter/issues/30

### CODE REVIEW

**Review by grumpyoldman-io — COMMENTED** [review]
I think this solves a lot of the issues, but I also noticed external dependencies relying on window (Torus labs one for instant). Which is automatically imported because it is used in the `wallets` package. But lets first validate these changes.

**Comment by grumpyoldman-io** [comment]
I've tested these packages in my nextjs project:

@solana/wallet-adapter-base
@solana/wallet-adapter-ledger
@solana/wallet-adapter-mathwallet
@solana/wallet-adapter-phantom
@solana/wallet-adapter-react
@solana/wallet-adapter-solflare
@solana/wallet-adapter-sollet
@solana/wallet-adapter-solong

and can confirm the import works, but the third party dependencies indeed still break:

```
xxx/node_modules/@project-serum/sol-wallet-adapter/dist/cjs/index.js:79
import EventEmitter from 'eventemitter3';

SyntaxError: Cannot use import statement outside a module
```

**Comment by jordansexton** [comment]
Interesting. I was trying not to add a build tool for this library besides tsc, but it may be unavoidable.

**Comment by jordansexton** [comment]
I've merged this, but will leave #30 open until I can integrate webpack/rollup/something this week.

**Comment by grumpyoldman-io** [comment]
@jordansexton Can I suggest Microbundle? I think that could hit the spot just right.

**Comment by jovincroninwilesmith** [comment]
Getting this same issue 

```
/node_modules/@project-serum/sol-wallet-adapter/dist/cjs/index.js:79
import EventEmitter from 'eventemitter3';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Comment by Hossman333** [comment]
As am i. 😊 I'll take a look at #30 issue to see what I can do.

**Comment by jordansexton** [comment]
Yeah, #30 has some possible workarounds. This library includes some external dependencies but doesn't transpile them, so it may come down to adding some config to Next / Webpack / Babel. Please let me know what you find out!

**Pull request merged**
