### PR TITLE
Enable strict ESM exports

### LINKED ISSUE #241: Create React App is broken by lack of default polyfills in Webpack 5
Edit by @jordansexton:

To anyone looking for a very good workaround right now, don't use Create React App. Just use the [react-ui-starter](https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/react-ui-starter) or [material-ui-starter](https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/material-ui-starter) projects with Parcel, or the [nextjs-starter](https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/nextjs-starter) project with Next.js, save yourself a huge hassle, and get much faster builds with SWC instead of Babel.

---

**Describe the bug**
Broken build with CRA v5, unable to resolve modules.

**To Reproduce**
1. Initialize a new CRA project. `npx create-react-app my-app-test`
2. Install and use any wallet-adapter packages
3. See error

```
BREAKING CHANGE: The request './adapter' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

**Solution**
Relative imports must include a file extension to follow ESM strict mode requirements introduced in Webpack 5. It's valid typescript to include `.js` extensions as part of the import path 🤯 :

example.ts

```typescript
import { Example } from './example.js';
```
compiles to

example.js
```javascript
import { Example } from './example.js';
```

### LINKED ISSUE #246: Next.js 12: Cannot find module useWalletModal
**Describe the bug**
When deploying to production, I'm seeing this error happen: 
Screen Shot 2022-01-05 at 9 58 15 PM

**To Reproduce**
1. Install the @solana/wallet-adapter-react-ui package in next.js
2. Set up the wallet connection
3. Use the WalletMultiButton
4. Refresh the page, and see the error. You can also see the error in deployment

**Expected behavior**
The `useWalletModal` should be provided

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 96

### PR DESCRIPTION
**Pull request by jordansexton**
This PR fixes #246 by causing all builds to produce .mjs files.

It doesn't address #241 yet, see https://github.com/solana-labs/wallet-adapter/pull/254#issuecomment-1008227270

It also removes the need to dynamically load the WalletProvider in Next's SSR, which will help with static page generation.

cc @cogoo @gpoole @stanleycyang

To test this, from the `strict-esm` branch:

```
yarn nuke
yarn
yarn build
```

This builds all the packages, but you'll get an error from the `react-ui-starter` package. This is because it's still using CRA v4, which doesn't handle the new imports.

However, if you then do this:

```
cd packages/starter/next-12-starter
yarn build
```

This builds now with no errors.

```
yarn dev
open http://localhost:3000
```

The page renders with no issues and the WalletAdapter buttons work.

We'll need to update the CRA v4 based starter projects to v5, which should fix this with no additional configuration.

### CODE REVIEW

**Comment by jordansexton** [comment]
Hmm, the situation with CRA v5 is more complicated than this:

```
Failed to compile.

Module not found: Error: Can't resolve 'stream' in '/Users/jordan/Work/Github/solana-labs/wallet-adapter/node_modules/cipher-base'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
	- install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "stream": false }
```

You can see from these very recent comments that the issue is not fixable without using React App Rewired or patching the Webpack config.

https://github.com/facebook/create-react-app/issues/11756#issuecomment-1002637667

https://github.com/facebook/create-react-app/issues/11756#issuecomment-1002766299

Craco won't work since it doesn't support v5 either.

There appear to be some other warnings during the build as well, e.g.

```
WARNING in ../../../node_modules/@solana/buffer-layout/lib/Layout.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/jordan/Work/Github/solana-labs/wallet-adapter/node_modules/@solana/buffer-layout/src/Layout.ts' file: Error: ENOENT: no such file or directory, open '/Users/jordan/Work/Github/solana-labs/wallet-adapter/node_modules/@solana/buffer-layout/src/Layout.ts'
 @ ../../../node_modules/@solana/web3.js/lib/index.browser.esm.js 6:0-54 1881:9-26 1890:14-33 1890:35-51 1890:63-79
 @ ./src/Wallet.tsx 10:0-48 22:33-46
 @ ./src/index.tsx 6:0-34 15:33-39
 ```

@cogoo I've pushed a `cra-5-starter` project as part of this PR. Any suggestions?

**Comment by gpoole** [comment]
Thanks @jordansexton! I had a go at setting this up to test on my project but unfortunately got the following error trying to build with Node 17.2.0:

<details>
<summary>jest error</summary>

```
lerna ERR! yarn run build exited 1 in '@solana/wallet-adapter-react-ui-starter'
lerna ERR! yarn run build stdout:
$ yarn clean && craco build
$ shx rm -rf build/*
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build stderr:

There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "jest": "26.6.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of jest was detected higher up in the tree:

  /Users/greg/Downloads/wallet-adapter/node_modules/jest (version: 27.4.7) 

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "jest" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if /Users/greg/Downloads/wallet-adapter/node_modules/jest is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls jest in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed jest.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!

error Command failed with exit code 1.
lerna ERR! yarn run build exited 1 in '@solana/wallet-adapter-react-ui-starter'
lerna WARN complete Waiting for 4 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
FAIL: 1
```
</details>

I ignored the above with `SKIP_PREFLIGHT_CHECK=true`, then, still on 17 I got:

<details>
<summary>hash error</summary>

```
lerna ERR! yarn run build exited 1 in '@solana/wallet-adapter-react-ui-starter'
lerna ERR! yarn run build stdout:
$ yarn clean && craco build
$ shx rm -rf build/*
Creating an optimized production build...
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build stderr:
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/greg/Downloads/wallet-adapter/node_modules/react-scripts/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/greg/Downloads/wallet-adapter/node_modules/react-scripts/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/greg/Downloads/wallet-adapter/node_modules/react-scripts/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/greg/Downloads/wallet-adapter/node_modules/react-scripts/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/greg/Downloads/wallet-adapter/node_modules/react-scripts/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/greg/Downloads/wallet-adapter/node_modules/react-scripts/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/greg/Downloads/wallet-adapter/node_modules/react-scripts/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/greg/Downloads/wallet-adapter/node_modules/react-scripts/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/greg/Downloads/wallet-adapter/node_modules/react-scripts/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/greg/Downloads/wallet-adapter/node_modules/react-scripts/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/greg/Downloads/wallet-adapter/node_modules/react-scripts/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/greg/Downloads/wallet-adapter/node_modules/react-scripts/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/greg/Downloads/wallet-adapter/node_modules/react-scripts/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/greg/Downloads/wallet-adapter/node_modules/react-scripts/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/Users/greg/Downloads/wallet-adapter/node_modules/react-scripts/scripts/build.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/greg/Downloads/wallet-adapter/node_modules/react-scripts/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/greg/Downloads/wallet-adapter/node_modules/react-scripts/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/greg/Downloads/wallet-adapter/node_modules/react-scripts/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/greg/Downloads/wallet-adapter/node_modules/react-scripts/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/greg/Downloads/wallet-adapter/node_modules/react-scripts/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/greg/Downloads/wallet-adapter/node_modules/react-scripts/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/greg/Downloads/wallet-adapter/node_modules/react-scripts/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/greg/Downloads/wallet-adapter/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.2.0
error Command failed with exit code 1.
lerna ERR! yarn run build exited 1 in '@solana/wallet-adapter-react-ui-starter'
lerna WARN complete Waiting for 5 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
FAIL: 1

```
</details>

Wound up just trying to build the dependencies for linking:

```
SKIP_PREFLIGHT_CHECK=true yarn build --scope "@solana/*" --ignore "@solana/*-starter" --ignore "@solana/wallet-adapter-example"
```

Unfortunately having a hard time linking from my external project into these Lerna packages. Haven't tried to do that with Lerna before, do you have any idea how to test it?

**Comment by jordansexton** [comment]
@gpoole I'm not sure I understand. These packages haven't been published yet, and you're also building the react-ui-starter package which uses CRA 4. This PR doesn't fix that yet.

**Comment by gpoole** [comment]
I was planning on using `npm link` to link the packages into my own project to help test the fix. Probably not really that different to your internal next template though, so might not add much anyway.

**Comment by jordansexton** [comment]
Published:
 - @solana/wallet-adapter-base@0.9.2
 - @solana/wallet-adapter-react@0.15.2
 - @solana/wallet-adapter-vue@0.4.3
 - @solana/wallet-adapter-example@0.18.0
 - @solana/wallet-adapter-nextjs-starter@0.8.0
 - @solana/wallet-adapter-ant-design@0.11.2
 - @solana/wallet-adapter-material-ui@0.16.2
 - @solana/wallet-adapter-react-ui@0.9.3
 - @solana/wallet-adapter-vue-ui@0.2.2
 - @solana/wallet-adapter-bitkeep@0.3.2
 - @solana/wallet-adapter-bitpie@0.5.2
 - @solana/wallet-adapter-blocto@0.5.2
 - @solana/wallet-adapter-clover@0.4.2
 - @solana/wallet-adapter-coin98@0.5.2
 - @solana/wallet-adapter-coinhub@0.3.2
 - @solana/wallet-adapter-ledger@0.9.2
 - @solana/wallet-adapter-mathwallet@0.9.2
 - @solana/wallet-adapter-phantom@0.9.2
 - @solana/wallet-adapter-safepal@0.5.2
 - @solana/wallet-adapter-slope@0.5.2
 - @solana/wallet-adapter-solflare@0.6.2
 - @solana/wallet-adapter-sollet@0.10.3
 - @solana/wallet-adapter-solong@0.9.2
 - @solana/wallet-adapter-tokenpocket@0.4.2
 - @solana/wallet-adapter-torus@0.11.3
 - @solana/wallet-adapter-wallets@0.14.2

**Pull request merged**
