### PR TITLE
Change network

### PR DESCRIPTION
**Pull request by tyirenkyi**
This PR aims to add the change network feature mentioned in #46. 

What's been done: 
1. Modal for react-ui
2. Custom Select component for react-ui
3. Context and provider for react-ui modal
4. Update ConnectionProvider to track endpoints and update connection

What's being worked on:
1. Standalone button for switching networks without a wallet connection

### CODE REVIEW

**Comment by tyirenkyi** [comment]
Check react-ui starter project on how to use the new `NetworkModalProvider`

**Comment by tyirenkyi** [comment]
@jordansexton could you take a look at this PR?

**Comment by SvenDowideit** [comment]
@jordansexton and @tyirenkyi how close is this to being merged? We have a network selector in our app, and i'm trying to start using the wallet-adapter for it too, and this is the last weird sync area :D

**Comment by jordansexton** [comment]
Not at all close. I wouldn't count on it landing, and it's not a high priority. If you need network selection, better to implement in your app.

**Comment by SvenDowideit** [comment]
mmmm, darn :) thanks.

**Comment by jordansexton** [comment]
Closing as we probably won't implement this at the application or adapter level.

We will soon [move away from requiring adapters](https://github.com/solana-labs/wallet-adapter/pull/384#issuecomment-1159115764) for every wallet, and the new wallet standard will have a network param in the relevant methods.

**Comment by neelsomani** [comment]
Folks, could you point me to the new wallet standard? We have several applications deploying with [custom RPCs](https://twitter.com/EclipseFND), and while we could create a new standard so they can support this feature to change networks, we'd prefer to adopt what y'all already have in mind. It is cited as one of the most popular pain points for us.

It sounds like Backpack and Solflare are on board to implement whatever is needed on their end if we can surface the relevant information via the wallet adapter or however else.

**Comment by jordansexton** [comment]
@neelsomani https://github.com/solana-labs/wallet-standard/tree/master/packages/core/features is where this would likely go. Please open an issue on that repo before sending a PR though.

For context, Backpack currently implements this as `window.backpack.connection` which uses a web3.js `Connection` object. This is probably a higher level interface than we'd want to expose.

We've avoided dependency on web3.js across the Wallet Standard, using raw bytes everywhere instead of web3.js types. Also consider that web3.js is [getting a planned rewrite](https://github.com/solana-labs/solana-web3.js/issues/1111).

**Pull request closed without merging**
