### PR TITLE
Update to mui-v5 (material-ui v5)

### LINKED ISSUE #168: Support mui v5 (material-ui 's new version)
**Is your feature request related to a problem? Please describe.**
Currently, the material-ui adapter is for material-ui v4.
mui v5 has been released recently: https://mui.com/blog/mui-core-v5/

**Describe the solution you'd like**
Codemods are available at: https://mui.com/guides/migration-v4/

**Additional context**
Creating this issue to start gauging interest in this. I might be able to create a PR if there's interest.

### PR DESCRIPTION
**Pull request by chrisirhc**
I opted to updating the existing starters instead of adding new `mui` folders.
I'm amenable to renaming the material-ui starters to `mui` or creating a new folder if we need to maintain backward compatibility for material-ui v4 users for a bit.

Also happy to split this up to 3 PRs for the material-ui-adapter, starter/material-ui, starter/example, if that's necessary.
Since this definitely became a pretty big PR.

Resolves #168

### CODE REVIEW

**Comment by jordansexton** [comment]
Thanks for this! Just got back from vacation, will review as soon as I can :)

**Comment by gaolingxiao** [comment]
has this merged yet?

**Comment by jordansexton** [comment]
I caught this PR up to some important changes that landed in master, reviewing now.

**Comment by jordansexton** [comment]
I checked it out, fixed the build, and ran the example.

Screen Shot 2021-12-15 at 4 03 40 PM
Screen Shot 2021-12-15 at 4 03 55 PM

I see some small styling issues like the caps, but it works!

**Comment by chrisirhc** [comment]
Great, let me know if there's anything you'd like me to address. I'm a little busy today but likely can respond from Monday onwards.

**Comment by jordansexton** [comment]
Thanks @chrisirhc. I merged in the latest master. If you're able to fix any styling issues, I can merge this next week.

**Comment by chrisirhc** [comment]
Fixed the text appearing in uppercase.
Here's a new screenshot:
image

**Comment by chrisirhc** [comment]
I'm looking into one other remaining styling issue that I found, that the menu doesn't overlap with the button:
image

If you see any other styling issues, let me know.

**Comment by chrisirhc** [comment]
I uploaded the current version at https://chrisirhc.github.io/wallet-adapter/example/ for easy checking/testing.

**Comment by chrisirhc** [comment]
Fixed the anchor issue and uploaded a new version to https://chrisirhc.github.io/wallet-adapter/example/

**Comment by jordansexton** [comment]
Looks great!

**Pull request merged**
