### PR TITLE
GIB💎WORK Bounty - Create NextJS 14 version

### PR DESCRIPTION
**Pull request by Manice18**
🤖 This pull request was created by https://app.gib.work/i/-oEl7_zF/create-nextjs-14-version 
 ⚡️ Payment for bounty is immediately sent to the contributor after merge.

### CODE REVIEW

**Comment by DuttaArghya** [comment]
how is this different from #870?

**Comment by Manice18** [comment]
> how is this different from #870?

Just saw your code too.
Maybe it's diff because I didn't use TailwindCSS 😅.

**Comment by DuttaArghya** [comment]
> > how is this different from #870?
> 
> Just saw your code too. Maybe it's diff because I didn't use TailwindCSS 😅.

yeah, right. :)
apart from the CSS framework choice, looks like we have huge similarities in our code, file structure, naming-convention, even README edits seem pretty close, no?

**Comment by Manice18** [comment]
> > > how is this different from #870?
> > 
> > Just saw your code too. Maybe it's diff because I didn't use TailwindCSS 😅.
> 
> yeah, right. :)
> apart from the CSS framework choice, looks like we have huge similarities in our code, file structure, naming-convention, even README edits seem pretty close, no?

Readme seems the same because both of us are using the same npx command to create it, xD.
And the components have the same name because docs have the same lol.

**Comment by DuttaArghya** [comment]
> > > > how is this different from #870?
> > > 
> > > 
> > > Just saw your code too. Maybe it's diff because I didn't use TailwindCSS 😅.
> > 
> > 
> > yeah, right. :)
> > apart from the CSS framework choice, looks like we have huge similarities in our code, file structure, naming-convention, even README edits seem pretty close, no?
> 
> Readme seems the same because both of us are using the same npx command to create it, xD. And the components have the same name because docs have the same lol.

my bad.  i meant the changes made to `package.json`. lol

**Comment by Manice18** [comment]
> > > > > how is this different from #870?
> > > > 
> > > > 
> > > > Just saw your code too. Maybe it's diff because I didn't use TailwindCSS 😅.
> > > 
> > > 
> > > yeah, right. :)
> > > apart from the CSS framework choice, looks like we have huge similarities in our code, file structure, naming-convention, even README edits seem pretty close, no?
> > 
> > Readme seems the same because both of us are using the same npx command to create it, xD. And the components have the same name because docs have the same lol.
> 
> my bad.  i meant the changes made to `package.json`. lol

I actually referenced it with the previous nextjs-starter and kept it the same except for the version.

**Comment by DuttaArghya** [comment]
> > > > > > how is this different from #870?
> > > > > 
> > > > > 
> > > > > Just saw your code too. Maybe it's diff because I didn't use TailwindCSS 😅.
> > > > 
> > > > 
> > > > yeah, right. :)
> > > > apart from the CSS framework choice, looks like we have huge similarities in our code, file structure, naming-convention, even README edits seem pretty close, no?
> > > 
> > > 
> > > Readme seems the same because both of us are using the same npx command to create it, xD. And the components have the same name because docs have the same lol.
> > 
> > 
> > my bad.  i meant the changes made to `package.json`. lol
> 
> I actually referenced it with the previous nextjs-starter and kept it the same except for the version.

nice work, man. have a great day.  :)

**Comment by Manice18** [comment]
> > > > > > > how is this different from #870?
> > > > > > 
> > > > > > 
> > > > > > Just saw your code too. Maybe it's diff because I didn't use TailwindCSS 😅.
> > > > > 
> > > > > 
> > > > > yeah, right. :)
> > > > > apart from the CSS framework choice, looks like we have huge similarities in our code, file structure, naming-convention, even README edits seem pretty close, no?
> > > > 
> > > > 
> > > > Readme seems the same because both of us are using the same npx command to create it, xD. And the components have the same name because docs have the same lol.
> > > 
> > > 
> > > my bad.  i meant the changes made to `package.json`. lol
> > 
> > I actually referenced it with the previous nextjs-starter and kept it the same except for the version.
> 
> nice work, man. have a great day.  :)

Same to you man. Cheers💪

**Comment by mcintyre94** [comment]
Thanks for your contribution! I'm going to close it though, because I don't think this is the most valuable repo to be contributing a Next 14 example. I appreciate that someone has opened a bounty asking for this on this repo, so sorry for the disappointment. The examples here have never been usable as-is, because they rely on `workspace` dependencies. This makes them useful for developing and testing `wallet-adapter`, and we don't want to lose that.

The best place to contribute this would be https://github.com/solana-developers/create-solana-dapp. This is intended to be used by developers as a quickstart for creating new dapps, so it serves exactly the purpose you're looking for here. It'll definitely help many more developers there. 

There's already an option to create a Next app there, which uses Next 13 with the `app/` directory. I'd suggest opening an issue in that repo to find out whether it'd be better to bump it to Next 14, or create a separate option between Next 13 and Next 14 if there are significant changes.

**Pull request closed without merging**
