### PR TITLE
add message signing support for solflare

### PR DESCRIPTION
**Pull request by Jeffrieh**
Solflare supports signing of messages, made some changes to the wallet adapter to support this.
let me know if any other changes have to be made.

### CODE REVIEW

**Comment by Jeffrieh** [comment]
Saw there's already a PR active, closing.

**Comment by Jeffrieh** [comment]
noticed there was already a similar PR open after creating this one, but this one should be ready to merge compared to the other one so i'll keep it open.

**Comment by jordansexton** [comment]
Thanks!

**Comment by jordansexton** [comment]
@Jeffrieh can you clarify whether the correct interface for this is `signMessage` (as implemented here) or `sign` (as in #147)? Also, is `Uint8Array.from(signature)` necessary if `signature` is already a `Uint8Array`?

**Comment by Jeffrieh** [comment]
Hi Jordan,

I can confirm signMessage is actually the correct interface, as per the docs on : https://docs.solflare.com/technical/connecting-your-solana-dapp-with-solflare

As for your second question, i believe you're actually right, small oversight on my part, since signature is already a Uint8Array, this would be sufficient : 

```
const { signature } = await wallet.signMessage(message, 'utf8');
return signature
```

**Pull request merged**
