### PR TITLE
add signMessage method

### PR DESCRIPTION
**Pull request by xiaobaixin**

### CODE REVIEW

**Comment by jordansexton** [comment]
For this to work, you'll need to extend like this: https://github.com/solana-labs/wallet-adapter/blob/fd543782d9fed22c564855308216dacfc75c0c32/packages/wallets/phantom/src/adapter.ts#L52

**Comment by xiaobaixin** [comment]
> For this to work, you'll need to extend like this:
> 
> https://github.com/solana-labs/wallet-adapter/blob/fd543782d9fed22c564855308216dacfc75c0c32/packages/wallets/phantom/src/adapter.ts#L52

**Comment by jordansexton** [comment]
It's okay, you don't need to close the PR! I just want you to make this change to it so that the API will work with the other packages.

**Comment by xiaobaixin** [comment]
yeah  i'll create new pr now

**Pull request closed without merging**
