### PR TITLE
Update TokenPocket's logo

### PR DESCRIPTION
**Pull request by chendatony31**
Update TokenPocket's logo

### CODE REVIEW

**Comment by jordansexton** [comment]
Looks good, can you also update the one here? https://github.com/solana-labs/wallet-adapter/tree/master/packages/wallets/icons

**Comment by chendatony31** [comment]
Sure, done @jordansexton

**Comment by jordansexton** [comment]
Thanks!

**Comment by chendatony31** [comment]
Any plan to update the npmjs package `@solana/wallet-adapter-tokenpocket` recently? 😄

**Comment by jordansexton** [comment]
@chendatony31 can you open a PR to bump the patch version?

**Pull request merged**
