### PR TITLE
WalletConnect

### PR DESCRIPTION
**Pull request by AlexBHarley**
# What is this?

A wallet adapter for WalletConnect (v2), enabling Solana dapps to be used by mobile wallets.

# How can I test it?

1. Open two browser windows, one with the `packages/starter/example` project running and one at https://react-wallet.walletconnect.com/
2. On the example app, click `Select Wallet` under React UI
3. Click WalletConnect
4. Click `Copy to clipboard` under the QR code
5. Paste the URI into the example wallet
6. Choose accounts to connect
7. Try actions

- [x] sign/send transactions
- [x] sign messages
- [x] re establishes connection on refresh
- [x] disconnecting

### CODE REVIEW

**Comment by jordansexton** [comment]
This is great! Is this used within SteakWallet on Solana now? Just wondering what wallets support WC2, and what to communicate to wallet teams that want to add support for it.

**Comment by AlexBHarley** [comment]
Yes it's been implemented in Steakwallet, just configure the dapp to only connect to mainnet and you're good to go.

### How should wallets proceed?

1. Read the [JSON-RPC specification for Solana WalletConnect](https://docs.walletconnect.com/2.0/json-rpc/solana). We're actually looking for feedback on some remaining methods that some dapps likely need: https://github.com/WalletConnect/walletconnect-docs/pull/137, https://github.com/WalletConnect/walletconnect-docs/pull/136 and https://github.com/WalletConnect/walletconnect-docs/pull/135
2. Read the [UX Considerations](https://docs.walletconnect.com/2.0/protocol/ux-considerations) to keep in mind when implementing WC support in your wallet

**Comment by antoineherzog** [comment]
It looks great. Any plan to have this PR merged soon? Crypto Please would like to implement Wallet Connect.

**Comment by AlexBHarley** [comment]
@jordansexton do you think this could be merged soon?

**Comment by jordansexton** [comment]
I'll try to review soon! A lack of wallets supporting WC2 has kept this from being prioritized and we've been a bit resource constrained.

**Comment by AlexBHarley** [comment]
@jordansexton hoping for a path forward here. If this was rebranded to be a Steakwallet specific adapter, rather than WalletConnect, would it speed up the process?

**Comment by jordansexton** [comment]
Merged with #418 since I don't have perms on your fork. I didn't want to hold this up any further, but I'd like to ask for a follow up PR to address an issue before we release the package --

All the adapters that load a third party SDK (some examples: [Torus](https://github.com/solana-labs/wallet-adapter/blob/71721308116452f07293bc8f543a6b7f094a75cb/packages/wallets/torus/src/adapter.ts#L74-L86), [Ledger](https://github.com/solana-labs/wallet-adapter/blob/71721308116452f07293bc8f543a6b7f094a75cb/packages/wallets/ledger/src/adapter.ts#L66-L78)) are designed to do this asynchronously in the `connect` function.

This is to minimize the initial load footprint of adapters and not load a bunch of libs before the user actually wants them. Could you update the implementation to do this?

**Pull request merged**
